name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install prerequisites
      run: |
        sudo apt update
        sudo apt install -y make nasm mkisofs
    
    - name: Create a makefile
      run: |
        cat <<EOF > Makefile
        all: build

        build:
          nasm -f bin -o kernel.bin src/kernel.asm
          mv kernel.bin bin/kernel.bin
          mkisofs -b kernel.bin -no-emul-boot -o kernel.iso bin/

        clean:
          rm -rvf kernel.bin
          rm -rvf kernel.iso
        EOF
    
    - name: Build
      run: make build

    - name: Clean
      run: make clean
